server:
  port: 8090

spring:
  application:
    name: core-api

  profiles:
    default: dev


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      highlight_sql: true
      auto_quote_keyword: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

  jackson:
    serialization:
      write-dates-as-timestamps: false

  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!

  #  elasticsearch:
  #    uris: http://115.94.72.198:9200
  #    username: elastic
  #    password: nhnacademy123!

  cloud:
    openfeign:
      enabled: true

  cache:
    jcache:
      config: classpath:cache/ehcache.xml
  servlet:
    multipart:
      enabled: true

aladin:
  api:
    key: ttbheej19982032001


springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true


management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logncrash:
  config:
    file-path: logs
    file-name: core-api-log
  app-key: Xyx7DoyszcG66ULx
  url: https://api-logncrash.cloud.toast.com
  version: 1.0.0
  host: aa-core-api
  platform: aa-core-api
  log:
    version: v2
    source: aa
    type: aa

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
