spring:
  application:
    name: core

  profiles:
    active: dev

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 20
    max-total: 40
    max-idle: 15
    min-idle: 10

  jackson:
    serialization:
      write-dates-as-timestamps: false

aladin:
  api:
    key: ttbheej19982032001


springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true
