spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: core-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hdm2ddl:
          auto: validate
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

api:
  gateway:
    host: localhost
    port: 8080

eureka:
  instance:
    instance-id: core-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: cacea6422cee4017b8af5edd24834165
      username: 6764281f095b4154ab34a04b4fea6b8d
      password: 3a23273e707b438e94f104f47ce7a7ba
  image:
    appkey: vyiy4M85i8mJ5mgP
    secretkey: fBlt6m4cSRJs07X05mhPBfmofWoBlcSU


